export default [
  {
    space: true,
    prettier: true,
    react: true,
    rules: {
      '@stylistic/lines-between-class-members': 'off',
      'capitalized-comments': 0,
      'import-x/extensions': 0,
      'import/no-unassigned-import': 0,
      'import-x/order': 0,
      'n/file-extension-in-import': 0,
      'no-bitwise': 0,
      'no-else-return': 0,
      'react/jsx-no-leaked-render': 0,
      'no-lonely-if': 0,
      'no-negated-condition': 0,
      'no-warning-comments': 0,
      'object-curly-spacing': ['error', 'always'],
      'object-shorthand': [
        'error',
        'always',
        {
          avoidExplicitReturnArrows: false,
        },
      ],
      'react/boolean-prop-naming': 0,
      'react/function-component-definition': 0,
      'react/jsx-no-duplicate-props': 0,
      'react/prefer-read-only-props': 0,
      'react/require-default-props': 0,
      'unicorn/filename-case': 0,
      'unicorn/no-array-callback-reference': 0,
      'unicorn/no-array-reduce': 0,
      'unicorn/no-fn-reference-in-iterator': 0,
      'unicorn/no-negated-condition': 0,
      'unicorn/numeric-separators-style': 0,
      'unicorn/prefer-global-this': 0,
      'unicorn/prefer-module': 0,
      'unicorn/prefer-node-protocol': 0,
      'unicorn/prefer-ternary': 0,
      'unicorn/prevent-abbreviations': 0,
      'unicorn/switch-case-braces': 0,
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'as',
          objectLiteralTypeAssertions: 'allow',
        },
      ],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-restricted-types': 'off',
      '@typescript-eslint/prefer-regexp-exec': 'off',
    },
  },
];
